---
- name: Enable puppet repository
  become: yes
  raw: wget https://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb && dpkg -i puppetlabs-release-pc1-xenial.deb && apt update

- name: Install puppetserver
  become: yes
  apt: "pkg={{ item }} force=yes state=present update_cache=yes cache_valid_time=3600"
  with_items:
  - puppetserver 
  - puppet-common
