---
- name: Bootstrap EC2 instance
  ec2:
    key_name: puppet
    group: "{{ security_group }}"
    instance_type: t2.medium
    image: ami-40d28157
    wait: yes
    wait_timeout: 500
    exact_count: 1
    count_tag:
      Name: puppetmaster
    instance_tags:
      Name: puppetmaster
    monitoring: yes
    vpc_subnet_id: subnet-59205673 
    assign_public_ip: yes
  register: ec2
  tags:
    - bootstrap

- name: Add new instances to host group
  add_host:
    hostname: "{{item.public_ip}}"
    groupname: deploy
  with_items: ec2.instances

- name: Wait for the instances to boot by checking the ssh port
  wait_for:
    host: "{{item.public_dns_name}}" 
    port: 22 
    delay: 60 
    timeout: 320 
    state: started
  with_items: ec2.instances

- name: Create a volume and attach
  ec2_vol: 
    volume_size: 20 
    instance: "{{item.id}}"
    delete_on_termination: yes
  with_items: ec2.instances
